
--creating nc_users Table

  CREATE TABLE "HR"."NC_USERS" 
   (	"USER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(255 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

-- SELECT * FROM NC_USERS;
 SELECT * FROM COMPLAINTS;
DELETE FROM COMPLAINTS
--insert into nc_users table
 INSERT INTO NC_USERS values(101,'prasad@gmail.com','1234pppp');
 
--CREATE complaints TABLE

  CREATE TABLE "HR"."COMPLAINTS" 
   (	"ACCOUNT_ID" VARCHAR2(100), 
	"BRANCHCODE" VARCHAR2(100), 
	"EMAIL" VARCHAR2(100), 
	"COMPLAINT_CATEGORY" VARCHAR2(100), 
	"DESCRIPTION" VARCHAR2(100), 
	"PRIORITY" VARCHAR2(100), 
	"STATUS" VARCHAR2(100), 
	"COMPLAINT_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;